version: '3.8'

services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_USER: 'gongbu'
      POSTGRES_PASSWORD: 'gongbu'
      POSTGRES_DB: 'gongbu'
    ports:
      - "5444:5432"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"

  sonic:
    image: valeriansaliou/sonic:v1.3.2
    ports:
      - "1492:1492"
    volumes:
      - "./sonic.cfg:/etc/sonic.cfg:ro"
      - "./data/dev/sonic/store/:/var/lib/sonic/store/:ro"
